from tkinter import *
win=Tk()
win.title('Periodic Table')
win.geometry('1300x700')

lbl=Label(win,text='Periodic Table',font=('Harrington',20))
lbl.pack()

h=Button(win,text='\nH\nHydrogen',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
li=Button(win,text='\nLi\nLithium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
na=Button(win,text='\nNa\nSodium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
k=Button(win,text='\nK\nPotassium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
rb=Button(win,text='\nRb\nRubidium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
cs=Button(win,text='\nCs\nCaesium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
fr=Button(win,text='\nFr\nFrancium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
be=Button(win,text='\nBe\nBeryllium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
mg=Button(win,text='\nMg\nMagnesium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
ca=Button(win,text='\nCa\nCalcium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
sr=Button(win,text='\nSr\nStrontium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
ba=Button(win,text='\nBa\nBarium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
ra=Button(win,text='\nRa\nRadium',width=7,height=3,bg='#ffcce0',font=('Times new roman',9))
sc=Button(win,text='\nSc\nScandium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
ti=Button(win,text='\nTi\nTitanium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
v=Button(win,text='\nV\nVanadium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
cr=Button(win,text='\nCr\nChromium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
mn=Button(win,text='\nMn\nManganese',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
fe=Button(win,text='\nFe\nIron',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
co=Button(win,text='\nCo\nCobalt',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
ni=Button(win,text='\nNi\nNickel',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
cu=Button(win,text='\nCu\nCopper',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
zn=Button(win,text='\nZn\nZinc',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
y=Button(win,text='\nY\nYttrium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
zr=Button(win,text='\nZr\nZirconium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
nb=Button(win,text='\nNb\nNiobium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
mo=Button(win,text='\nMo\nMolybdenum',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
tc=Button(win,text='\nTc\nTechnetium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
ru=Button(win,text='\nRu\nRuthenium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
rh=Button(win,text='\nRh\nRhodium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
pd=Button(win,text='\nPd\nPalladium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
ag=Button(win,text='\nAg\nSilver',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
cd=Button(win,text='\nCd\nCadmium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
lanthanides=Button(win,text='\n\nLanthanides',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
hf=Button(win,text='\nHf\nHafnium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
ta=Button(win,text='\nTa\nTantalum',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
w=Button(win,text='\nW\nTungsten',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
re=Button(win,text='\nRe\nRhenium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
os=Button(win,text='\nOs\nOsmium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
ir=Button(win,text='\nIr\nIridium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
pt=Button(win,text='\nPt\nPlatinum',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
au=Button(win,text='\nAu\nGold',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
hg=Button(win,text='\nHg\nMercury',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
actinides=Button(win,text='\n\nActinides',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
rf=Button(win,text='\nRf\nRutherfordium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
db=Button(win,text='\nDb\nDubnium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
sg=Button(win,text='\nSg\nSeaborgium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
bh=Button(win,text='\nBh\nBohrium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
hs=Button(win,text='\nHs\nHassium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
mt=Button(win,text='\nMt\nMeitnerium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
ds=Button(win,text='\nDs\nDarmstadtium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
rg=Button(win,text='\nRg\nRoentgenium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))
cn=Button(win,text='\nCn\nCopernicium',width=7,height=3,bg='#99ccff',font=('Times new roman',9))

h.place(x=15,y=60)
li.place(x=15,y=120)
na.place(x=15,y=180)
k.place(x=15,y=240)
rb.place(x=15,y=300)
cs.place(x=15,y=360)
fr.place(x=15,y=420)

be.place(x=80,y=120)
mg.place(x=80,y=180)
ca.place(x=80,y=240)
sr.place(x=80,y=300)
ba.place(x=80,y=360)
ra.place(x=80,y=420)

sc.place(x=145,y=240)
ti.place(x=210,y=240)
v.place(x=275,y=240)
cr.place(x=340,y=240)
mn.place(x=405,y=240)
fe.place(x=470,y=240)
co.place(x=535,y=240)
ni.place(x=600,y=240)
cu.place(x=665,y=240)
zn.place(x=730,y=240)

y.place(x=145,y=300)
zr.place(x=210,y=300)
nb.place(x=275,y=300)
mo.place(x=340,y=300)
tc.place(x=405,y=300)
ru.place(x=470,y=300)
rh.place(x=535,y=300)
pd.place(x=600,y=300)
ag.place(x=665,y=300)
cd.place(x=730,y=300)

lanthanides.place(x=145,y=360)
hf.place(x=210,y=360)
ta.place(x=275,y=360)
w.place(x=340,y=360)
re.place(x=405,y=360)
os.place(x=470,y=360)
ir.place(x=535,y=360)
pt.place(x=600,y=360)
au.place(x=665,y=360)
hg.place(x=730,y=360)

actinides.place(x=145,y=420)
rf.place(x=210,y=420)
db.place(x=275,y=420)
sg.place(x=340,y=420)
bh.place(x=405,y=420)
hs.place(x=470,y=420)
mt.place(x=535,y=420)
ds.place(x=600,y=420)
rg.place(x=665,y=420)
cn.place(x=730,y=420)

win.mainloop()